Repository jooYeonIya/JJHOTEL, pull requests merged in 2024-10, with the labels that each got.

#10 Design/07
  .gitignore
  index.html
  src/App.jsx
  src/components/About.jsx
  src/components/Kakao.jsx
  src/css/About.css
  src/images/about_information.jpg
Labels: enhancement, design

#12 design: Dining / Pool 화면의 배경 이미지 & 설명 텍스트 추가, 스크롤 위치에 따라 화면 변경 (#11)
  src/components/Facilities.jsx
  src/css/Facilities.css
  src/images/facilities_dining.jpg
  src/images/facilities_pool.jpg
Labels: design

#13 Design/09
  package-lock.json
  package.json
  src/App.jsx
  src/components/CustomButton.jsx
  src/components/Reservation.jsx
  src/components/ReservationCalendar.jsx
  src/components/TitleLabel.jsx
  src/css/App.css
  src/css/index.css
Labels: design

#18 refactor: 폴더 이동
  src/components/About.jsx
  src/components/Header.jsx
  src/components/Reservation.jsx
  src/css/Header.css
  src/pages/About.jsx
  src/pages/Facilities.jsx
  src/pages/Reservation.jsx
  src/pages/Rooms.jsx
Labels: design

#19 Design/09
  src/components/Counter.jsx
  src/components/CustomButton.jsx
  src/components/CustomInfo.jsx
  src/components/Header.jsx
  src/components/ReservationCalendar.jsx
  src/components/RoomInfo.jsx
  src/pages/Reservation.jsx
  src/pages/ReservationInputCustomInfo.jsx
  src/pages/RoomDescription.jsx
  src/pages/Rooms.jsx
  src/text/titles.jsx
Labels: design

#20 Design/03
  src/components/Header.jsx
  src/css/Header.css
  src/pages/Home.jsx
  src/pages/Reservation.jsx
  src/pages/Rooms.jsx
Labels: design

#25 Design/22
  src/components/Header.jsx
  src/css/Home.css
  src/images/home_about.jpg
  src/images/home_facilities.jpg
  src/images/home_reservation.jpg
  src/images/home_rooms.jpg
  src/images/hotel_main.jpg
  src/pages/CheckReservation.jsx
  src/pages/Home.jsx
Labels: design

#26 Design/22
  src/pages/Home.jsx
Labels: design

#27 Feature/21
  package-lock.json
  package.json
  server/server.js
  src/components/RoomInfo.jsx
  src/pages/Reservation.jsx
  src/pages/ReservationInputCustomInfo.jsx
  src/pages/Rooms.jsx
Labels: enhancement

#30 Feature/28
  server/server.js
  src/components/RoomInfo.jsx
  src/pages/RoomDescription.jsx
Labels: enhancement

#34 Design/24
  server/server.js
  src/components/ReservationInfo.jsx
  src/pages/CheckReservation.jsx
Labels: design

#46 Design/44
  index.html
  src/components/Kakao.jsx
  src/components/MainImageContainer.jsx
  src/css/About.css
  src/css/App.css
  src/css/Facilities.css
  src/css/Header.css
  src/images/home_main.jpg
  src/images/hotel_favicon.ico.png
  src/images/rooms_deluxe_1.jpg
  src/images/rooms_deluxe_2.jpg
  src/images/rooms_deluxe_3.jpg
  src/images/rooms_deluxe_4.jpg
  src/images/rooms_standard_1.jpg
  src/images/rooms_standard_2.jpg
  src/images/rooms_standard_3.jpg
  src/images/rooms_standard_4.jpg
  src/images/rooms_suite_1.jpg
  src/images/rooms_suite_2.jpg
  src/images/rooms_suite_3.jpg
  src/images/rooms_suite_4.jpg
  src/pages/About.jsx
Labels: design

#48 Design/44
  hotel_favicon.ico.png
  index.html
  src/components/ReservationInfo.jsx
  src/components/RoomInfo.jsx
  src/css/About.css
  src/css/App.css
  src/css/CheckReservation.css
  src/css/CustomButton.css
  src/css/Facilities.css
  src/css/Header.css
  src/css/Home.css
  src/css/Reservation.css
  src/css/ReservationInputCustomInfo.css
  src/css/RoomDescription.css
  src/css/Rooms.css
  src/pages/CheckReservation.jsx
  src/pages/RoomDescription.jsx
Labels: enhancement, design
